### ISSUE TITLE
Set the default Winning Field Value parameter to "Use Winning Field's Alias"

### ISSUE THREAD

**Issue by djarrard** [djarrard/ArcGIS-Cross-Table-Tools#6]
Both tools have a parameter that allow you to control whether the value indicating which field had the highest value is driven by the winning fields proper name or its alias. Given the common use of this tool with BA variables, which have cryptic field names, it has been suggested that we switch the default so that the alias's are used by default.

This should be an easy change but want to get additional feedback from users before implementing this change

**Comment by djarrard-zz** [comment]
This enhancement has been implemented
